%YAML:1.0
annotators:
    - CollectionReader
    - ImagePreprocessor
    - RegionFilter
    - NormalEstimator
    - PlaneAnnotator
    - PointCloudClusterExtractor
    - ImageSegmentationAnnotator
    - ClusterMerger
    - Cluster3DGeometryAnnotator
    - ClusterColorHistogramCalculator
    - FeatureAnnotator
    - CaffeAnnotator
    - PCLFeatureExtractor
    - TFBroadcaster
    - ObjectIdentityResolution
    - BeliefToKnowRob
    - StorageWriter

cw_assumption:
    - red_spotted_bowl
    - red_spotted_plate
    - red_spotted_cup
    - fork_blue_plastic
    - fork_red_plastic
    - fork_ycb
    - knife_blue_plastic
    - knife_red_plastic
    - knife_ycb
    - reine_butter_milch
    - voll_milch
    - jod_salz
